version: '3'

services:
  nginx:
    build: ./requirements/nginx
    restart: always
    ports:
      - "4443:443"
    volumes:
      - wordpress:/var/www/
    networks:
      - inc
  wordpress:
    build: ./requirements/wordpress
    env_file:
      - .env
    restart: always
    volumes:
      - wordpress:/var/www/
    expose:
      - "9000"
    networks:
      - inc
  mariadb:
    build: ./requirements/mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/mysql
    expose:
      - "3306"
    networks:
      - inc

networks:
  inc:
    driver: bridge
    driver_opts:
      type: 'none' 								
      o: 'bind'
      device: '/home/data/wordpress' 	
volumes:
  wordpress:
    driver: local

  db-data:
    driver: local
