version: '3'

services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/
    networks:
      - inc
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    env_file:
      - .env
    restart: always
    volumes:
      - wordpress:/var/www/
    expose:
      - "9000"
    networks:
      - inc
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/mysql
    expose:
      - "3306"
    networks:
      - inc
  redis:
    build: ./requirements/bonus/redis
    container_name: redis
    restart: always
    env_file:
      - .env
    expose:
      - "6379"
    networks:
      - inc
  ftp:
    build: ./requirements/bonus/ftp
    container_name: ftp
    restart: always
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    networks:
      - inc
  adminer:
    build: ./requirements/bonus/adminer
    container_name: adminer
    restart: always
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - inc
  portfolio:
    build: ./requirements/bonus/portfolio
    container_name: portfolio
    restart: always
    env_file:
      - .env
    ports:
      - "18080:80"
    networks:
      - inc

networks:
  inc:
    driver: bridge
volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '$HOME/data/wordpress'

  db-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '$HOME/data/database'
